name: GitHub - Activity - Readme
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    run-ons: ubuntu-latest

  steps:
    -uses: actions/checkout@v2
    -uses: jamesgeorge077/hithub-activity-readme@master
    env:
     GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}